name: Docker Deploy to Azure

on:
  push:
    branches:
      - main  # Skript sa spustí pri každom pushnutí do main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: bpjurajregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image
        run: |
          # Vytvoríme image s unikátnym tagom podľa ID commitu
          docker build -t bpjurajregistry.azurecr.io/bp-web:${{ github.sha }} .
          docker push bpjurajregistry.azurecr.io/bp-web:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Voliteľné, ale odporúčané
          images: 'bpjurajregistry.azurecr.io/bp-web:${{ github.sha }}'